export const APP_WILL_MOUNT = "APP_WILL_MOUNT";
export const APP_WILL_UNMOUNT = "APP_WILL_UNMOUNT";
export const SET_LOCATION_URL = "SET_LOCATION_URL";
export const APP_WILL_NAVIGATE = "APP_WILL_NAVIGATE";
