export const SIGN_IN = "SIGN_IN";
export const USERNAME_CHANGED = "USERNAME_CHANGED";
export const PASSWORD_CHANGED = "PASSWORD_CHANGED";
export const REMEMBER_ME_CHANGED = "REMEMBER_ME_CHANGED";

export const SET_METHOD_SELECTION_OPEN = "SET_METHOD_SELECTION_OPEN";
export const SET_WEBAUTHN_SUPPORTED = "SET_WEBAUTHN_SUPPORTED";

export const SET_METHOD = "SET_METHOD";
