export const STATE_CHANGE_WEBAUTHN = "STATE_CHANGE_WEBAUTHN";
export const REGISTER_WEBAUTHN = "REGISTER_WEBAUTHN";
export const SIGN_IN_ERROR_WEBAUTHN = "SIGN_IN_ERROR_WEBAUTHN";
export const SIGN_IN_SUCCESS_WEBAUTHN = "SIGN_IN_SUCCESS_WEBAUTHN";
