version: '3'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
    command: /bin/sh -c "while sleep 1000; do :; done"
    ports:
      - "8080:8080"  # Adjust according to the app's port
      - "3000:3000"  # Adjust according to the React app's port
